#server:
#  port: 8095
spring:
  application:
    name: msvc-student
    #provicional solo para levantar el microservice
  config:
    import: optional:configserver:http://localhost:8888

#  datasource:
#    #driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/studentdb
#    username: root
#    password: admin
#  jpa:
#    hibernate:
#      ddl-auto: create
##    properties:
##      hibernate:
##        generate-ddl: true
##        show-sql: true
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
