#server:
#  port: 9090
spring:
  application:
    name: msvc-course
    #provicional solo para levantar el microservice
  config:
    import: optional:configserver:http://localhost:8888

#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/coursedb
#    username: postgres
#    password: admin
#  jpa:
#    hibernate:
#      ddl-auto: create
#    #    properties:
#    #      hibernate:
#    #        generate-ddl: true
#    #        show-sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

